stages:
  - lint
  - test
  - build
  - docker
  - deploy

variables:
  NODE_ENV: production
  DOCKER_TLS_CERTDIR: ""

# ---------------- CACHE ----------------
cache:
  paths:
    - tmdb-app/node_modules/

# ---------------- LINT ----------------
lint:
  image: node:20-alpine
  stage: lint
  script:
    - cd tmdb-app
    - npm ci
    - npm run lint || echo "Lint skipped or errors ignored"
  allow_failure: true
  cache:
    paths:
      - tmdb-app/node_modules/

# ---------------- TEST ----------------
test:
  image: node:20-alpine
  stage: test
  script:
    - cd tmdb-app
    - npm ci
    - npm test -- --watch=false --passWithNoTests
  allow_failure: true
  cache:
    paths:
      - tmdb-app/node_modules/

# ---------------- BUILD ----------------
build:
  image: node:20-alpine
  stage: build
  script:
    - cd tmdb-app
    - npm ci
    - CI=false npm run build
  artifacts:
    paths:
      - tmdb-app/build/
    expire_in: 1 hour

# ---------------- DOCKER ----------------
docker:
  image: docker:25
  stage: docker
  services:
    - docker:25-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache bash curl aws-cli
    - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$AWS_REGISTRY"
  script:
    - docker build -t $AWS_REGISTRY/$APP_NAME:$CI_PIPELINE_IID ./tmdb-app
    - docker tag $AWS_REGISTRY/$APP_NAME:$CI_PIPELINE_IID $AWS_REGISTRY/$APP_NAME:latest
    - docker push $AWS_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
    - docker push $AWS_REGISTRY/$APP_NAME:latest

# ---------------- DEPLOY ----------------
deploy:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add --no-cache bash openssh-client rsync gettext
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts
  script:
    # Ensure directories exist on EC2
    - ssh $EC2_USER@$EC2_IP "mkdir -p /home/$EC2_USER/tmdb_challenge/nginx"

    # Copy nginx folder
    - rsync -av tmbd-app/nginx/ $EC2_USER@$EC2_IP:/home/$EC2_USER/tmdb_challenge/nginx/


    # Copy docker-compose.yml with env vars
    - envsubst < docker-compose.yml | ssh $EC2_USER@$EC2_IP "cat > /home/$EC2_USER/tmdb_challenge/docker-compose.yml"


    # Run Docker Compose on EC2
    - ssh $EC2_USER@$EC2_IP "
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_REGISTRY &&
        cd /home/$EC2_USER/tmdb_challenge &&
        docker compose down &&
        docker compose up -d --build --force-recreate --remove-orphans
      "




